import Head from "next/head"
import styles from "../styles/Home.module.css"
import Header from "../components/Header"
import Hero from "../components/HeroSection"
import About from "../components/About"
import Slider from "../components/Slider"
import CoinTicker from "../components/CoinTicker"
import Footer from "../components/Footer"
import FAQ from "../components/Faq"
import Vslider from "../components/Vslider"

import LotteryEntrance from "../components/LotteryEntrance"
import { useMoralis } from "react-moralis"
import "bootstrap/dist/css/bootstrap.min.css"
import Ticker from "../components/Tickers"
import "mdb-react-ui-kit/dist/css/mdb.min.css"
import ScrollToTop from "react-scroll-to-top"
import List from "../components/WinnerList"

const supportedChains = ["31337", "4"]

export default function Home() {
    const { isWeb3Enabled, chainId } = useMoralis()

    return (
        <div className={styles.container}>
            <Head>
                <title>Casino BitRoyale</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;900&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Header />
            <Hero />

            <About />

            <Slider />
            <FAQ />
            <Vslider />
        
            <CoinTicker />
            <Footer />
            <ScrollToTop smooth />
            {isWeb3Enabled ? (
                <div>
                    {supportedChains.includes(parseInt(chainId).toString()) ? (
                        <div className="flex flex-row">
                            <LotteryEntrance className="p-8" />
                        </div>
                    ) : (
                        <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
                    )}
                </div>
            ) : (
                <div></div>
            )}
        </div>
    )
}
